#!/usr/bin/env python3
"""Build the compact semantic runtime asset for the selected stone cards."""

from __future__ import annotations

import hashlib
import json
from collections import Counter
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / (
    "art/generated/one_off/letter_card_surfaces_2026-08-25/retrodiffusion/"
    "option2_carved_tide_stone__82521.png"
)
REVIEW = ROOT / (
    "art/generated/one_off/letter_card_surfaces_2026-08-25/"
    "alphabet_extrapolation_stone_wide_palette/"
    "alphabet_2a_stonewashed_atkinson_contact_sheet.png"
)
REVIEW_MANIFEST = REVIEW.with_name("render_manifest.json")
HEADER = ROOT / "firmware/PhonicsGame/CardStoneAsset.h"
REPORT = ROOT / "art/letter_cards/generated/stone_card_report.json"

SOURCE_SHA256 = "80bb7f65419280532000c5399e159334f607a9087b67dbf31adc53e62da9b0df"
REVIEW_SHA256 = "a6c5f49d04bd28dda05e58170ae68e1d1b1f99f8b51fda4f46566847419a5e46"
SOURCE_BBOX = (20, 7, 108, 120)

ROLE_DEFINITIONS = (
    (0, "transparent", None),
    (1, "main_body", (95, 143, 160)),
    (2, "body_shadow", (53, 103, 122)),
    (3, "deep_crevice", (11, 42, 60)),
    (4, "pale_mineral", (216, 238, 240)),
    (5, "deep_slate", (18, 74, 96)),
    (6, "mid_mineral", (145, 183, 190)),
    (7, "white_chip", (247, 255, 255)),
    (8, "cyan_glint", (39, 211, 208)),
)

LETTER_COLORS = (
    0x8B0A, 0x5BCD, 0x732F, 0x7BC9, 0x536F, 0x830D, 0x5BAB,
    0x6B10, 0x8B89, 0x53CE, 0x7AEE, 0x6BA9, 0x5B70, 0x8AEA,
    0x53AB, 0x62F0, 0x83A9, 0x53AF, 0x82ED, 0x5BCA, 0x72F0,
    0x8B09, 0x5BAD, 0x72EF, 0x73C9, 0x5370,
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def fail(message: str) -> None:
    raise RuntimeError(message)


def validate_review() -> dict:
    if sha256(REVIEW) != REVIEW_SHA256:
        fail("approved stonewashed contact sheet hash changed")
    manifest = json.loads(REVIEW_MANIFEST.read_text())
    if manifest.get("output", {}).get("sha256") != REVIEW_SHA256:
        fail("approved review manifest does not match its contact sheet")
    actual = tuple(int(item["base_rgb565"], 16) for item in manifest["palette"])
    if actual != LETTER_COLORS:
        fail("approved review palette changed")
    if manifest.get("openai_image_generation_used") is not False:
        fail("approved review provenance is invalid")
    return manifest


def semantic_pixels() -> tuple[list[int], Counter[int]]:
    if sha256(SOURCE) != SOURCE_SHA256:
        fail("selected RD 82521 source hash changed")
    image = Image.open(SOURCE).convert("RGBA")
    if image.size != (128, 128) or image.getbbox() != SOURCE_BBOX:
        fail("selected RD 82521 dimensions or alpha bounds changed")
    by_rgb = {rgb: role_id for role_id, _, rgb in ROLE_DEFINITIONS if rgb}
    pixels: list[int] = []
    for rgba in image.crop(SOURCE_BBOX).get_flattened_data():
        if rgba[3] == 0:
            pixels.append(0)
        elif rgba[:3] in by_rgb and rgba[3] == 255:
            pixels.append(by_rgb[rgba[:3]])
        else:
            fail(f"unexpected RD stone pixel {rgba}")
    counts = Counter(pixels)
    if set(counts) != set(range(9)):
        fail("selected RD stone does not contain all semantic roles")
    return pixels, counts


def pack_nibbles(pixels: list[int]) -> bytes:
    packed = bytearray()
    for index in range(0, len(pixels), 2):
        low = pixels[index]
        high = pixels[index + 1] if index + 1 < len(pixels) else 0
        packed.append(low | (high << 4))
    return bytes(packed)


def format_values(values: list[str], per_line: int, indent: str = "    ") -> str:
    return "\n".join(
        indent + ", ".join(values[index:index + per_line]) + ","
        for index in range(0, len(values), per_line)
    )


def build_header(packed: bytes, counts: Counter[int]) -> str:
    color_values = [f"0x{value:04X}" for value in LETTER_COLORS]
    count_values = [f"{counts[index]}u" for index in range(9)]
    byte_values = [f"0x{value:02X}" for value in packed]
    return f"""#pragma once

#include <stdint.h>

#ifndef PROGMEM
#define PROGMEM
#endif

namespace phonics_game {{

// Generated by scripts/build_letter_card_asset.py from the exact selected
// Retro Diffusion rd_pro seed 82521 source. The four-bit values retain its
// alpha silhouette and eight semantic mineral regions without storing 26
// full-color bitmaps.
inline constexpr uint16_t kStoneSourceWidth = 88;
inline constexpr uint16_t kStoneSourceHeight = 113;
inline constexpr uint32_t kStoneSourcePixelCount =
    static_cast<uint32_t>(kStoneSourceWidth) * kStoneSourceHeight;
inline constexpr uint32_t kStonePackedBytes = (kStoneSourcePixelCount + 1) / 2;
// Near-black blue-grey shadow selected as #040B11 and quantized to RGB565.
// The former 0x0204 decoded as a conspicuous green strip on the AMOLED.
inline constexpr uint16_t kStoneShadowColor = 0x0042;

enum StoneRole : uint8_t {{
  kStoneTransparent = 0,
  kStoneMainBody = 1,
  kStoneBodyShadow = 2,
  kStoneDeepCrevice = 3,
  kStonePaleMineral = 4,
  kStoneDeepSlate = 5,
  kStoneMidMineral = 6,
  kStoneWhiteChip = 7,
  kStoneCyanGlint = 8,
  kStoneRoleCount = 9,
}};

// Permanent a-z learning anchors selected in the approved stonewashed v4
// contact sheet. Never regenerate or reorder this table.
inline constexpr uint16_t kStoneLetterColors[26] = {{
{format_values(color_values, 7)}
}};

inline constexpr uint16_t kStoneRolePixelCounts[kStoneRoleCount] = {{
{format_values(count_values, 9)}
}};

inline const uint8_t kStonePackedRoles[kStonePackedBytes] PROGMEM = {{
{format_values(byte_values, 16)}
}};

inline uint8_t stoneRoleAt(uint16_t x, uint16_t y) {{
  const uint32_t index = static_cast<uint32_t>(y) * kStoneSourceWidth + x;
  const uint8_t packed = kStonePackedRoles[index >> 1];
  return (index & 1u) ? static_cast<uint8_t>(packed >> 4)
                      : static_cast<uint8_t>(packed & 0x0Fu);
}}

}}  // namespace phonics_game
"""


def main() -> None:
    review_manifest = validate_review()
    pixels, counts = semantic_pixels()
    packed = pack_nibbles(pixels)
    header = build_header(packed, counts)
    HEADER.write_text(header)
    report = {
        "schema_version": 1,
        "status": "passed",
        "selected_direction": "2A v5 stonewashed with Atkinson",
        "production_asset": True,
        "builder": str(Path(__file__).resolve().relative_to(ROOT)),
        "builder_sha256": sha256(Path(__file__).resolve()),
        "source": str(SOURCE.relative_to(ROOT)),
        "source_sha256": SOURCE_SHA256,
        "source_alpha_bbox": list(SOURCE_BBOX),
        "review_contact_sheet": str(REVIEW.relative_to(ROOT)),
        "review_contact_sheet_sha256": REVIEW_SHA256,
        "review_manifest_sha256": sha256(REVIEW_MANIFEST),
        "openai_image_generation_used": False,
        "new_generation_calls": 0,
        "semantic_dimensions": [88, 113],
        "semantic_role_counts": {
            name: counts[role_id] for role_id, name, _ in ROLE_DEFINITIONS
        },
        "packed_bytes": len(packed),
        "packed_sha256": hashlib.sha256(packed).hexdigest(),
        "header": str(HEADER.relative_to(ROOT)),
        "header_sha256": sha256(HEADER),
        "palette": [f"0x{value:04X}" for value in LETTER_COLORS],
        "review_palette_strategy": review_manifest["palette_strategy"],
    }
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(json.dumps(report, indent=2) + "\n")
    print(f"Wrote {HEADER.relative_to(ROOT)} ({len(packed)} packed bytes)")
    print(f"Wrote {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    try:
        main()
    except (OSError, KeyError, ValueError, RuntimeError) as error:
        raise SystemExit(f"letter-card asset build failed: {error}")
